from sqlalchemy import Column, Integer, Float, ForeignKey
from database import Base

class ParamConductor(Base):
    __tablename__ = "param_conductores"
    memoria_id = Column(Integer, ForeignKey("memorias.id"), primary_key=True)
    n = Column(Integer, default=2)
    d_mm = Column(Float, default=28.0)
    as_m = Column(Float, default=0.07)
    m_s = Column(Float, default=1.955)
    As_mm2 = Column(Float, default=610.0)
    l = Column(Float, default=11.5)
    a = Column(Float, default=3.0)
    li = Column(Float, default=1.5)
    fes = Column(Float, default=0.433)
    h = Column(Float, default=15.0)
    V = Column(Float, default=30.0)
    Cz = Column(Float, default=1.0)
    Gf = Column(Float, default=0.85)
    Cf = Column(Float, default=1.0)
    t_ice = Column(Float, default=0.0)
    w_ice = Column(Float, default=8820.0)
    Ik3_kA = Column(Float, default=40.0)
    Tk1 = Column(Float, default=0.16)
    f_sys = Column(Integer, default=50)
    S_sup = Column(Float, default=100000.0)
    E_eff_GPa = Column(Float, default=55.0)
    cth_e18 = Column(Float, default=0.27)

class ResultConductor(Base):
    __tablename__ = "result_conductores"
    memoria_id = Column(Integer, ForeignKey("memorias.id"), primary_key=True)
    Fc = Column(Float)
    FI = Column(Float)
    w_tot = Column(Float)
    FW = Column(Float)
    w_res = Column(Float)
    Fst = Column(Float)
    d_viento = Column(Float)
    bh_viento = Column(Float)
    Fp = Column(Float)
    r = Column(Float)
    d1 = Column(Float)
    T = Column(Float)
    Tres = Column(Float)
    d_end_iec = Column(Float)
    dk_ieee = Column(Float)
    d_max_iec = Column(Float)
    dm_ieee = Column(Float)
    zeta_iec = Column(Float)
    zeta_ieee = Column(Float)
    phi_iec = Column(Float)
    phi_ieee = Column(Float)
    psi_iec = Column(Float)
    psi_ieee = Column(Float)
    Ft_iec = Column(Float)
    Ft_ieee = Column(Float)
    Ff_iec = Column(Float)
    Ff_ieee = Column(Float)
    CD_iec = Column(Float)
    CD_ieee = Column(Float)
    CF = Column(Float)
    fed = Column(Float)
    bh_iec = Column(Float)
    bh_ieee = Column(Float)
    a_min_iec = Column(Float)
    a_min_ieee = Column(Float)
